force-app/main/default/objects/Discount_Type__c/Discount_Type__c.object-meta.xml
<CustomObject>
    <label>Discount Type</label>
    <nameField>
        <label>Discount Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discount Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Discount_Type__c/fields/Specific_Day__c.field-meta.xml
<CustomField>
    <fullName>Specific_Day__c</fullName>
    <label>Specific Day</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SpecificDayDiscountStrategy.cls
public class SpecificDayDiscountStrategy implements DiscountStrategy {
    private Decimal specificDay;

    public SpecificDayDiscountStrategy() {}

    public void initialize(Discount_Type__c discountType) {
        this.specificDay = discountType.Specific_Day__c;
    }

    public Decimal applyDiscount(Decimal discountedPrice, Decimal basePrice) {
        Datetime now = Datetime.now();
        Integer currentDayOfMonth = now.day();
        return currentDayOfMonth == specificDay ? discountedPrice : basePrice;
    }
}